version: '3'
services:
    web:
        container_name: nginx
        ports:
            - "8080:80"
        image: nginx

##Volumes
version: '3'
services:
    web:
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - "vol2:/usr/share/nginx/html"
        image: nginx
volumes:
    vol2:

##Variables
version: '3'
services:
    db:
        container_name: mysql
        ports:
            - "3306:3306"
        image: mysql:5.7
        environment: 
            - "MYSQL_ROOT_PASSWORD=1234567"


##Red
version: '3'
services:
    web:
        container_name: nginx2
        ports:
            - "8081:80"
        image: httpd
        networks: 
            - net-test
    web2:
        container_name: nginx3
        ports:
            - "8082:80"
        image: httpd
        networks: 
            - net-test
networks:
  net-test:


##Limitado
version: '3'
services:
    web:
        container_name: web
        image: web-test
        build:
            context: .
            dockerfile: DockerFile
            version: '3.7'
            services:
                web:
                    container_name: nginx
                    image: nginx:alpine
                    deploy:
                        resources:
                          limits:
                            cpus: '0.50'
                            memory: 50M
                          reservations:
                            cpus: '0.25'
                            memory: 20M

##Reinicios
version: '3'
services:
    test:
        container_name: test
        build: .
        image: restart-image
        restart: no, always, on-failure, unless-stopped

##MariaDB + WordPress
version: '3'
 
services:
  db:
    container_name: wp-mysql
    image: mariadb
    volumes:
       - $PWD/data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    ports:
       - "3307:3306"
    expose:
      - "3307"
    networks:
       - my_net
    restart: on-failure
 
  wp:
    depends_on:
       - db
    container_name: wp-web
    volumes:
       - "$PWD/html:/var/www/html"
    image: wordpress
    ports:
       - "8010:80"
    environment:
       WORDPRESS_DB_HOST: "db:3306"
       WORDPRESS_DB_USER: "wordpress"
       WORDPRESS_DB_PASSWORD: "wordpress"
    networks:
       - my_net

networks:
  my_net:       

