version: '3.7'
services:
    web:
        container_name: nginx
        image: nginx:alpine
        deploy:
            resources:
              limits:
                cpus: '0.50'
                memory: 50M
              reservations:
                cpus: '0.25'
                memory: 20M